allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  1799b2bf-9e35-4f66-9b9c-80fbfe4ada8a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-19T09:11:11+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 58d2e05b-360b-4049-837d-a7ab70654fb6 # Button Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e02c6f9f-31c0-4096-8388-3b3f68da8bf6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2720036a-54f1-403e-9c37-80fce92d49d8
        userCondition: null
    thumbFieldKey: null
handle: buttonsToPage
hasTitleField: false
icon: null
name: 'Buttons Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
