allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  e8a43de6-0cc1-48ad-bf5f-3f8bcd8cab61:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T06:59:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d6d32a20-0ec5-4262-887f-7c6c55d96491
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T10:21:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 48922ed3-f535-4fed-9f81-9b7c5093f00e # List
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51726d9c-c469-4d39-8535-1f3bf4688f9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T07:02:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 532d7638-9f59-41af-91d2-46ddf87a3911 # Additional Info Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39b2e74c-7a3a-4177-b616-54cfd9c5caca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7858526-4a8e-44d8-abad-daa834898df5
        userCondition: null
    thumbFieldKey: null
handle: calendarModule
hasTitleField: true
icon: null
name: 'Calendar Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
