allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  79a7f5f3-8eed-4bb6-ba6e-b11b1f191399:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T10:13:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c0cdd2d-52e4-4732-a1d3-ac6ff82ffba4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c59afe1-b448-47ba-becc-851d7571889d
        userCondition: null
    thumbFieldKey: null
handle: contactFormModule
hasTitleField: true
icon: null
name: 'Contact Form Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
