allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  efe406a6-d684-4ba2-8306-9d2c3036879f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T06:46:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 474d1616-901e-4692-9fbe-1127c865de08
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T06:48:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3e8024eb-30e0-48f7-b719-1cac2c426042 # Button to Page 
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cd6c7e2-e347-41aa-9c4d-12d8a70eec43
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0b5ce7f-891e-47bb-8c58-8966f60d2cd6
        userCondition: null
    thumbFieldKey: null
handle: coursesSlider
hasTitleField: true
icon: null
name: 'Courses Slider Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
