allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  26db7bf8-c4c3-4009-affd-8c9f44dc75fa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T06:26:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b3f55d2-eded-4d85-ba27-53a5e110e56d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T06:26:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7ac416d2-61ef-4830-9fae-614415c30087 # Question Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78989851-80f7-45a8-a5c5-9254dcfad631
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-26T06:41:33+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 58d2e05b-360b-4049-837d-a7ab70654fb6 # Button Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb6ce000-3132-4cde-a237-1407dfd12ede
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a6c68639-b851-4e5e-a397-1c88b9e5275b
        userCondition: null
    thumbFieldKey: null
handle: faqModule
hasTitleField: true
icon: null
name: 'FAQ Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
