allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  6336a98f-e3ed-425f-b4b7-f03c940b05e8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-19T07:58:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 36dca454-5bf3-422e-b397-abb58dda5bbc # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f1de150-73c6-4dbe-9846-812131eef0c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-16T10:17:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7104f57b-112f-4c96-84cf-eda1c75fe796 # Textfield
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23d14294-bc3f-498e-b12b-82cc0a6398b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T07:58:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3e8024eb-30e0-48f7-b719-1cac2c426042 # Button to Page 
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0d22345-3af6-4dc3-94d0-97c92ce8d342
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d2f15f8-6e88-4233-809c-2cd2c7d1c8a0
        userCondition: null
    thumbFieldKey: null
handle: footerImageCard
hasTitleField: false
icon: null
name: 'Footer Image Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
