allowLineBreaksInTitles: false
color: yellow
description: null
fieldLayouts:
  86540a5a-2cb2-4a45-9e12-30f2dabf52c6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-18T15:38:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 763ca421-f258-4780-bc89-bf75a2eb3d6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T08:45:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfddac30-3c70-417e-a79d-05e574d4ce9b # Header Module
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fe04e99-1640-4815-a2ce-a87d98748160
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T08:45:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62984608-1c07-4a47-8888-964d4e3e06b1 # Feature Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b59a619-2793-481a-8fc4-79df698131d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1e7b46c-7d78-4b39-b928-c41deaa061a1
        userCondition: null
    thumbFieldKey: null
handle: groupsSection
hasTitleField: true
icon: null
name: 'Groups Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
