allowLineBreaksInTitles: false
color: yellow
description: null
fieldLayouts:
  55757e00-306b-4f6f-82c5-7287fa4a6802:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-18T15:39:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67acceac-0c41-48b8-83ad-7d956b8a8245
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T08:44:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfddac30-3c70-417e-a79d-05e574d4ce9b # Header Module
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57af46d6-6025-4621-8560-098cf75e5f36
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-16T09:51:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bc978765-b473-4a75-b703-5f8ec09931df # Groups
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bb3edc9-f83e-41af-a6a3-8ed3c6ef56b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-16T14:01:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 24de20be-1f1e-4b0a-922c-c1d79fdd59e7 # Calendar Section
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5784c623-46c1-4464-a496-b5b6480811aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T08:44:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62984608-1c07-4a47-8888-964d4e3e06b1 # Feature Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d30a9f56-8e77-488d-838f-4f3a9269b10f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d06568c1-cb61-48dd-9b92-5af8fa388c49
        userCondition: null
    thumbFieldKey: null
handle: groupClassSection
hasTitleField: true
icon: null
name: 'Group Class Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
