allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  2b58bfa5-33de-4ae4-97ff-6e137054e241:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T06:26:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3718223e-c041-44fd-acae-60b1890c5980
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T06:28:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7104f57b-112f-4c96-84cf-eda1c75fe796 # Textfield
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5735615a-226b-4fd2-80bb-b7eb8b1b757d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T06:28:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e0d3261a-1f53-4699-8019-52cc167ef7a8 # Feature Card Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe18b90-d31b-445d-9e85-32151bd11842
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8da554da-63fb-4026-9ce5-e31426263d44
        userCondition: null
    thumbFieldKey: null
handle: highlightsModule
hasTitleField: true
icon: null
name: 'Highlights Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
