allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  a4b904fe-9230-4b7b-91b6-61c5406fd7e3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-19T07:22:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74f18289-6c43-4a7a-80ae-5e019d661cd2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T07:29:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 915d4267-6824-4406-ab65-3099eaa85a2e # Address
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5985d2ce-dfd9-41c8-9b7e-686596b7e276
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-05-19T07:29:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f9ce81c-6377-48f1-8b5b-b5b2daefb9c1 # Phone Number
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4f5b542-6e0d-4029-95fe-24d080dffc9a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-05-19T07:29:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5416109a-5864-4bdf-9179-ee951c51cfd8 # Email
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 444acea6-c1e7-4aba-a2e3-2eccf8c09bc6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-05-19T07:29:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d9f677d9-2588-446d-abe7-d2721bfa0293 # Opening Hours
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 091f69c6-61d5-45a0-b041-e7fe11b90b1a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-05-19T07:29:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 532d7638-9f59-41af-91d2-46ddf87a3911 # Additional Info Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 058a7452-16a7-46d8-9da1-64336166082c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e39f7aa4-9eaa-472f-927b-adf0532eb8d3
        userCondition: null
    thumbFieldKey: null
handle: locationCard
hasTitleField: true
icon: null
name: 'Location Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
