isPublic: false
name: 'Private Schema'
scope:
  - 'sites.731c4afc-3bf9-4c58-a826-7db0350cadfd:read' # master-project
  - 'sections.c3b49286-4ca2-4801-9d33-2a3e31e1807d:read' # Home
  - 'sections.84547fdc-05c1-4c3c-a280-9b7fb6166e32:read' # Example Entry
  - 'volumes.21950e08-1320-46dd-b9f3-8ddae1b3aa50:read' # Images
  - 'categorygroups.ed370231-a5e5-4af1-bd6a-98735fcda9fb:read' # Example Category
  - 'directive:parseRefs'
  - 'directive:transform'
