columnSuffix: null
handle: alternateHeadline
instructions: null
name: 'Alternate Headline'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
