columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - cfdda943-4543-410c-bc0e-592e3074258b
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - f42ccb7d-f6b1-4efe-be0f-f658e318a2d4
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:22:00+00:00'
                            9:
                              - uid
                              - f8ebe533-8f46-4872-be7e-c4e137d36e66
                            12:
                              - fieldUid
                              - de42d2ef-eced-4823-8667-8e4fab66c577 # Label
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:22:00+00:00'
                            9:
                              - uid
                              - 1d3ff3eb-4df9-4460-ab4b-47dd266eaf04
                            12:
                              - fieldUid
                              - 193ea414-f1e5-4711-89bd-3cbbab7875b2 # Link General
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:22:00+00:00'
                            9:
                              - uid
                              - 89659b82-d9aa-4486-9fad-7d43ffad2cc4
                            12:
                              - fieldUid
                              - f329a093-89dd-4fd5-92c6-beb411ab6692 # Is Call To Action
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:22:00+00:00'
                            9:
                              - uid
                              - 39a2cb2b-9369-4a90-bd08-3308502e0db0
                            12:
                              - fieldUid
                              - 4f0c1aaa-3d24-4d5c-b4f5-5a93f74a84f9 # Open In New Tab
            4:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
