columnSuffix: null
handle: buttonMatrix
instructions: null
name: 'Button Matrix'
searchable: false
settings:
  createButtonLabel: 'New Button'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 575b634d-670d-44e7-ad05-dcbc49edcc76 # Button To Page
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards-grid
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
