columnSuffix: null
handle: clubSelection
instructions: null
name: 'Club Selection'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\LevelConditionRule
              -
                - uid
                - e82af743-c126-4b20-bfcf-ff0df6fdd787
              -
                - operator
                - '='
              -
                - value
                - '1'
              -
                - maxValue
                - ''
              -
                - step
                - 1
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:e011b6d5-dcbb-4da3-9dce-001b650b9f46' # Club
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
