columnSuffix: null
handle: groupType
instructions: null
name: 'Group Type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  source: 'group:b4e69c12-ef16-40cd-9c21-2556a3f9a56f' # Group
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
