columnSuffix: null
handle: headerModule
instructions: null
name: 'Header Module'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 2e79fd9d-0168-4081-a171-a2eac3badd34
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - ef2b7d83-7046-4286-82eb-615d9fcdf65f
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-18T15:56:07+00:00'
                            9:
                              - uid
                              - 0efe7dfa-9311-4894-b0f3-364e9a0f8061
                            12:
                              - fieldUid
                              - 36dca454-5bf3-422e-b397-abb58dda5bbc # Image
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 25
                            8:
                              - dateAdded
                              - '2026-05-19T10:26:57+00:00'
                            9:
                              - uid
                              - 43657c0b-d734-4133-8bab-6ca776a67d95
                            12:
                              - fieldUid
                              - a0d5380d-65ee-47ee-b0f1-33b3bb1247b6 # Alternate Headline
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 75
                            8:
                              - dateAdded
                              - '2026-05-19T09:19:11+00:00'
                            9:
                              - uid
                              - f5b26faf-e602-4303-a0bd-876d1e7b4cd8
                            11:
                              - elementCondition
                              -
                                __assoc__:
                                  -
                                    - elementType
                                    - craft\elements\ContentBlock
                                  -
                                    - fieldContext
                                    - global
                                  -
                                    - class
                                    - craft\elements\conditions\ElementCondition
                                  -
                                    - conditionRules
                                    -
                                      - { __assoc__: [[class, craft\fields\conditions\LightswitchFieldConditionRule], [uid, 08e726f9-f89e-47ad-90cb-d9d2db2da155], [value, true], [fieldUid, a0d5380d-65ee-47ee-b0f1-33b3bb1247b6], [layoutElementUid, 43657c0b-d734-4133-8bab-6ca776a67d95]] } # Alternate Headline
                            12:
                              - fieldUid
                              - 65c7cd75-f5f7-4fe0-b069-b06ca1934c55 # Headline
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T14:15:20+00:00'
                            9:
                              - uid
                              - 4e4cd640-bbd9-4314-844d-0586002e0fe2
                            12:
                              - fieldUid
                              - 4f2f5e21-b32e-486f-bbd1-715d51495863 # Introduction Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-18T15:56:07+00:00'
                            9:
                              - uid
                              - 7c30393c-3565-4cdc-984e-048c83090c0c
                            12:
                              - fieldUid
                              - 58d2e05b-360b-4049-837d-a7ab70654fb6 # Button Matrix
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-06-10T10:38:40+00:00'
                            9:
                              - uid
                              - 1810bb18-6681-4ae4-91ce-848032fe1d2c
                            12:
                              - fieldUid
                              - a0cb62d5-86dc-4094-814b-2de94b970f5a # Show Big Arrow
            4:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
