columnSuffix: null
handle: headerModuleMultimedia
instructions: null
name: 'Header Module Multimedia'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 355b3b67-9880-4220-b03b-b09aef9323cd
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - 7d57479c-c2b7-4524-bbf6-85de947fbc88
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:57:00+00:00'
                            9:
                              - uid
                              - f197ecfb-6de9-4cf5-8617-753ab89a07b0
                            12:
                              - fieldUid
                              - 44bac8d3-1669-4754-bead-2a54431edf78 # Media Element
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-19T06:57:00+00:00'
                            9:
                              - uid
                              - 74d7a7f5-8692-4543-8084-f19697004ab3
                            12:
                              - fieldUid
                              - 4f2f5e21-b32e-486f-bbd1-715d51495863 # Introduction Text
            4:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
