columnSuffix: null
handle: hideHeader
instructions: null
name: 'Hide Header'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
