columnSuffix: null
handle: isGroupClass
instructions: null
name: 'Is Group Class'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
