columnSuffix: null
handle: locationCardDisplay
instructions: null
name: 'Location Card Display'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Show switch'
        -
          - value
          - showSwitch
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Show both'
        -
          - value
          - showBoth
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Show one'
        -
          - value
          - showOne
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
