columnSuffix: null
handle: mediaElement
instructions: null
name: 'Media Element'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 9eb410e0-6f6d-4d9b-9733-1e6bbd3321db
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - fbba44bd-e53e-4cbe-98ac-eb438e9f8e07
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-12T13:51:18+00:00'
                            9:
                              - uid
                              - baa17933-e62d-4efc-a716-65ad37e327e3
                            12:
                              - fieldUid
                              - 1e170cea-f2aa-4dcd-8ad2-1d251c61be53 # Media Type
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-12T13:51:18+00:00'
                            9:
                              - uid
                              - 4964b534-53ba-4ce6-a5f6-c12d6ddfc93e
                            11:
                              - elementCondition
                              -
                                __assoc__:
                                  -
                                    - elementType
                                    - craft\elements\ContentBlock
                                  -
                                    - fieldContext
                                    - global
                                  -
                                    - class
                                    - craft\elements\conditions\ElementCondition
                                  -
                                    - conditionRules
                                    -
                                      - { __assoc__: [[class, craft\fields\conditions\OptionsFieldConditionRule], [uid, 6f159fad-98c0-4ec1-b11d-348c7b9067f7], [operator, in], [values, [image]], [fieldUid, 1e170cea-f2aa-4dcd-8ad2-1d251c61be53], [layoutElementUid, baa17933-e62d-4efc-a716-65ad37e327e3]] } # Media Type
                            12:
                              - fieldUid
                              - 36dca454-5bf3-422e-b397-abb58dda5bbc # Image
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - width
                              - 100
                            8:
                              - dateAdded
                              - '2026-05-12T13:51:18+00:00'
                            9:
                              - uid
                              - 3323ffaf-61a4-45d1-9060-ab6962ac862b
                            11:
                              - elementCondition
                              -
                                __assoc__:
                                  -
                                    - elementType
                                    - craft\elements\ContentBlock
                                  -
                                    - fieldContext
                                    - global
                                  -
                                    - class
                                    - craft\elements\conditions\ElementCondition
                                  -
                                    - conditionRules
                                    -
                                      - { __assoc__: [[class, craft\fields\conditions\OptionsFieldConditionRule], [uid, 2de0c9cc-dc06-4c6f-a120-2989e3b87a60], [operator, in], [values, [video]], [fieldUid, 1e170cea-f2aa-4dcd-8ad2-1d251c61be53], [layoutElementUid, baa17933-e62d-4efc-a716-65ad37e327e3]] } # Media Type
                            12:
                              - fieldUid
                              - 08fe3d45-2931-409c-9555-8afc00decda7 # Video
            4:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
