columnSuffix: null
handle: metadataList
instructions: 'Only add additional global meta tags here. Page-specific title and description tags are automatically pulled from each page, and adding them here can cause conflicts. Default global values can be set in the fields above'
name: 'Metadata List'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Type
            -
              - handle
              - type
            -
              - width
              - ''
            -
              - type
              - select
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Description
            -
              - handle
              - description
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Content
            -
              - handle
              - content
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
