columnSuffix: null
handle: position
instructions: null
name: Position
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  source: 'group:cddab166-f11e-4253-9940-1781dd7526c7' # Position
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
