dateModified: 1782810180
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      page: Entries
      type: native
    -
      key: singles
      page: Entries
      type: native
    -
      heading: Pages
      key: 'heading:7b2e4470-6586-45b6-839e-881ce01047bb'
      page: Entries
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:bb66069f-40f5-4f42-a7fd-21fef987c6b6' # Feature
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:cf6922f9-6cbd-4c4a-b7e7-65bba55e8cfa' # Specials
      page: Entries
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:e8b0c6b4-54c0-448d-8d0c-6ee41ce9345b' # Group Class
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Locations
      key: 'heading:123b5318-7832-44e2-8ba7-367f96c4abfb'
      page: Entries
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:e011b6d5-dcbb-4da3-9dce-001b650b9f46' # Club
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Team
      key: 'heading:36d051ae-980b-45b0-b3b7-e444a5cadbdc'
      page: Entries
      type: heading
    -
      key: 'section:ead07398-7b50-4558-9d45-db3e07f8c010' # Trainer
      page: Entries
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:c5140b51-0128-49af-9fc0-63fe79c12377' # Team Member
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: base@left.studio
  fromName: manhattan
  transportType: craft\mail\transportadapters\Sendmail
fs:
  data:
    hasUrls: true
    name: Data
    settings:
      path: volumes/data
    type: craft\fs\Local
    url: '@web/volumes/data'
  images:
    hasUrls: true
    name: Images
    settings:
      path: volumes/images
    type: craft\fs\Local
    url: '@web/volumes/images'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: volumes/transforms
    type: craft\fs\Local
    url: '@web/volumes/transforms'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: volumes/videos
    type: craft\fs\Local
    url: '@web/volumes/videos'
meta:
  __names__:
    0c017e24-6889-49f0-bdd2-058a139c9f1d: Data # Data
    0d6ee8f1-7a37-4ffb-9851-b1f50d4baf16: 'Image 600x' # Image 600x
    1c42fe9b-6979-4b47-8507-4fb9c233e5ae: Answer # Answer
    1d1e70bf-a278-465e-a64d-dfaa1661e193: Navigation # Navigation
    1d4e550e-a2bd-4fd7-8b89-c23095c1f395: 'Feature Section' # Feature Section
    2daf6ec4-ddd0-4991-b944-17506d810f7b: Shorthand # Shorthand
    2fbb02d0-7852-4eee-b721-807b931e788f: 'FAQ Section' # FAQ Section
    3a3779ad-ff4a-43ac-9875-963dca20b4b7: Navigation # Navigation
    3bb810a7-10e1-457f-9193-c7bb3a0ac292: 'Hardfacts Module' # Hardfacts Module
    3cd942f2-76c1-4400-b304-8ab5131be0ec: Membership # Membership
    3e5a24b6-3631-46f4-8baf-6975ec9e8e2b: 'Headline Text Module' # Headline Text Module
    3e8024eb-30e0-48f7-b719-1cac2c426042: 'Button to Page ' # Button to Page 
    4c6e825a-41ed-4b29-b9e6-13d83e2d675d: plain # plain
    4e467547-468e-4edb-9dcb-04801550f11d: 'Large Textfield' # Large Textfield
    4f0c1aaa-3d24-4d5c-b4f5-5a93f74a84f9: 'Open In New Tab' # Open In New Tab
    4f2f5e21-b32e-486f-bbd1-715d51495863: 'Introduction Text' # Introduction Text
    4f9ce81c-6377-48f1-8b5b-b5b2daefb9c1: 'Phone Number' # Phone Number
    4f86f4d9-f71e-4b7c-a1af-90e971944d08: 'Show Textfield' # Show Textfield
    5c5b1734-0179-4e73-a005-8900d305a5a8: 'Big Numbers Matrix' # Big Numbers Matrix
    05c6e9dc-1fc7-46a8-bbee-2c8138640bd8: Bold # Bold
    5e0d7bb4-8904-49ac-ac02-07a8b46945db: 'Bold Italic' # Bold Italic
    5e443f56-1947-4a31-a57c-c42a8c786557: 'Group Class Section' # Group Class Section
    5ee08050-7a65-4d7c-b428-7bbb3237c5f7: 'Club Brunn' # Club Brunn
    6d1f3d8a-4521-4f71-b4c8-23144725cbcb: 'Image Link' # Image Link
    7ac416d2-61ef-4830-9fae-614415c30087: 'Question Matrix' # Question Matrix
    7c4eb080-4557-4579-95f3-71701e831541: 'Club Card Matrix' # Club Card Matrix
    07d6dc4e-abab-414c-a938-4ddd636b9326: 'Buttons Module' # Buttons Module
    7e6dc66b-8d9a-456d-b368-6adfa0d7fba2: 'Image Width' # Image Width
    8a088675-caf5-4ab8-844c-7cfaf573d635: 'Big Number Text' # Big Number Text
    08a6e0ce-2fd8-4438-9350-0ade8aa7c567: 'Club Card' # Club Card
    8e6efe14-710c-4a78-9d2e-203007d30ac3: 'Club Wien' # Club Wien
    8e435383-a3e3-4c17-b718-a705e57b169d: 'FAQ Module' # FAQ Module
    9d8b28f3-10fe-4a22-9a06-0a3575ba15e5: Trainers # Trainers
    9e6015e7-07b1-474b-9437-2db9dec246a1: 'Club Section' # Club Section
    9fa6c3db-85f7-4431-831a-05a8249b0e26: 'Metadata Title' # Metadata Title
    9fca2092-c923-4410-94d5-0400708027ba: 'Show Buttons' # Show Buttons
    11dedd21-c9e4-4490-8ed2-ee30e10e3b4d: 'Accessibility Section' # Accessibility Section
    22a36ab3-e897-459a-815e-5a6d8c10025c: 'Trial Section' # Trial Section
    24de20be-1f1e-4b0a-922c-c1d79fdd59e7: 'Calendar Section' # Calendar Section
    31bb27d5-2fe2-4d1e-9a8f-24f46a3e7ca7: 'Media Type' # Media Type
    33cc55e5-c4ca-4af2-9eef-afec393747a7: 'Big Text Module' # Big Text Module
    36b9a6dd-d003-4f96-97bd-ecea80ecf0e5: 'Courses List Module' # Courses List Module
    36dca454-5bf3-422e-b397-abb58dda5bbc: Image # Image
    40b9212d-f977-40ad-b0ff-4cc1159a90af: Privacy # Privacy
    43dd2356-ba3d-4c0f-9dc7-ef6f8103a49c: Home # Home
    44bac8d3-1669-4754-bead-2a54431edf78: 'Media Element' # Media Element
    47fe71d6-0187-4525-8aaf-f52a573080a9: 'Club Card Display' # Club Card Display
    56c73aa1-4354-459f-8cc7-993a0bd12c3e: Position # Position
    58d2e05b-360b-4049-837d-a7ab70654fb6: 'Button Matrix' # Button Matrix
    59d7b4d5-411d-4579-918f-b41e4d19ba72: 'Specials Matrix' # Specials Matrix
    62ba4443-5b16-497a-9ee2-c2d12826a0b1: Jobs # Jobs
    65c7cd75-f5f7-4fe0-b069-b06ca1934c55: Headline # Headline
    65d375a7-319f-4479-82d2-f4343153b5f5: 'Team Member Section' # Team Member Section
    67bcebe2-888f-48c8-ad51-af89afcd1294: 'About Image Module' # About Image Module
    71b1773a-7e86-4d60-aa39-2b8f34b04bb8: 'Club Hardfacts Module' # Club Hardfacts Module
    77a9e634-565d-4610-8aea-d10dd619f000: Privacy # Privacy
    79d1e5f4-2146-4516-824b-a229efa17dbd: Button # Button
    85bf4b4f-4f28-4742-9bb7-1497231dc4bb: 'Footer Rows' # Footer Rows
    85c82572-807b-4e9f-8821-7ebda95fa357: 'Is Group Class' # Is Group Class
    88efd9f7-ec26-40b4-8150-94c677f28535: AGB # AGB
    88ff0e90-825c-4a73-adfe-26509a81c57e: Trial # Trial
    89a65ca6-59b1-4161-a8ca-e27dc33a1765: 'Social Links' # Social Links
    90cf3bd4-0d3f-4dc7-b2d7-595f1c8a8163: 'Trainer List Module' # Trainer List Module
    90d3f788-c9d1-4627-ab27-f84dc281f938: 'Hide Header' # Hide Header
    95c359c6-6a6b-492f-82cb-e3cb0f3cc89d: 'Footer Image Card' # Footer Image Card
    96b9defa-8f83-48da-8cf9-a3e2a79d855d: Video # Video
    96def785-a23f-48de-87f4-560f4ccb827b: Subcourses # Subcourses
    171d9cb7-63ac-4af2-b3f9-62769a033638: 'Jobs Section' # Jobs Section
    178af4fd-504f-4a96-947b-0b24da24fcaf: 'Location Cards' # Location Cards
    193ea414-f1e5-4711-89bd-3cbbab7875b2: 'Link General' # Link General
    285ad9a6-8c9b-40ad-a742-0b0e3c7fa7dc: 'Floor Plan Module' # Floor Plan Module
    310af722-4e91-4858-a3c5-35d1117e8a4e: 'AGB Section' # AGB Section
    493fa733-1597-4434-a9b8-f99336eccc7c: Question # Question
    532d7638-9f59-41af-91d2-46ddf87a3911: 'Additional Info Text' # Additional Info Text
    575b634d-670d-44e7-ad05-dcbc49edcc76: 'Button To Page' # Button To Page
    580fcb11-05c5-49cc-8fa6-47376fb12a2a: 'Courses Slider Module' # Courses Slider Module
    599c2594-7f7c-47e8-ab7f-5f15ea9d8f90: 'Textfield with Links' # Textfield with Links
    656a4014-1234-4b64-a057-b43309b68deb: 'Highlights Module' # Highlights Module
    731c4afc-3bf9-4c58-a826-7db0350cadfd: manhattan-de # manhattan-de
    785e3132-3133-4a2f-bec2-ef13854661b7: 'Club Hardfact Matrix' # Club Hardfact Matrix
    805ad2ef-e4c4-4f2d-a103-7ad68f04d32a: Enabled # Enabled
    861c6252-90ad-422d-b3bc-8eb31c71d798: Link # Link
    915d4267-6824-4406-ab65-3099eaa85a2e: Address # Address
    1756d8f1-31e3-4b0b-a923-3edc67ae2d63: 'Public Schema' # Public Schema
    3966bd14-5f7b-4ecf-b3bf-13bfcc0bcfcf: 'Feature Card' # Feature Card
    5228acaf-dbbf-4aac-b0b0-0c1c55e94b4a: 'Website Description' # Website Description
    5365ef59-c050-4702-82ab-876962749a48: 'Website Title' # Website Title
    5446d600-e88a-4d58-b876-2d5124956541: Accessibility # Accessibility
    6147a940-8c22-46a2-8719-b8518c60469b: 'Specials Section' # Specials Section
    6306dc46-c811-4480-a328-91c03807e2bc: 'Big Numbers Module' # Big Numbers Module
    7104f57b-112f-4c96-84cf-eda1c75fe796: Textfield # Textfield
    7400a4d7-0804-410e-8b70-9ae7926180a0: 'Membership Section' # Membership Section
    8319de11-8b0e-487f-83c2-5032ef70e346: Footer # Footer
    9364ddc6-965c-4ed2-b5d5-0a63cba3a05e: 'Contact Section' # Contact Section
    21950e08-1320-46dd-b9f3-8ddae1b3aa50: Images # Images
    47737df3-bfb9-4362-a499-d55dc0930606: 'Column Matrix' # Column Matrix
    48922ed3-f535-4fed-9f81-9b7c5093f00e: List # List
    56115c68-4440-4d24-ba3d-20420576a6a8: FAQ # FAQ
    69307dd8-eb06-43e3-8188-b4df5b23d2e1: 'Image 800x' # Image 800x
    71587f8d-c96c-42cb-a02c-1bd2227eff68: 'Calendar Module' # Calendar Module
    75421d42-40ba-4970-97ed-4f6cfbe07aa3: Signature # Signature
    94105fd8-47a5-4c58-9ac1-b9bdc86ac4e4: 'Image Gallery' # Image Gallery
    317902b0-411f-45d2-88c2-ca5f3bb66ca1: Calendar # Calendar
    329399c3-cf0b-4184-b8cf-111844590e07: Footer # Footer
    614813c6-21cb-4c1a-bb3b-f1373d4c80fe: 'Metadata Description' # Metadata Description
    973845f1-1777-4565-9b1f-44ad04497aba: Metadata # Metadata
    2975263d-b404-4627-ac32-18b3c5a59c08: 'Header Module Multimedia' # Header Module Multimedia
    5416109a-5864-4bdf-9179-ee951c51cfd8: Email # Email
    7964280e-24cd-41ca-8361-48886524226f: 'Image Icon' # Image Icon
    9078555c-ae88-4692-92ea-caa40af67d16: Column # Column
    37199222-1eda-4089-bcdd-633eae1c3d9f: 'List Item' # List Item
    55203975-9b97-4196-9cf1-d1fc2f976a5b: 'Trainer Card' # Trainer Card
    62984608-1c07-4a47-8888-964d4e3e06b1: 'Feature Matrix' # Feature Matrix
    a0cb62d5-86dc-4094-814b-2de94b970f5a: 'Show Big Arrow' # Show Big Arrow
    a0d5380d-65ee-47ee-b0f1-33b3bb1247b6: 'Alternate Headline' # Alternate Headline
    a2cae9f8-a8d7-4405-bb16-8546f16f6e4c: Text # Text
    a4ce1c73-5ce1-4af3-b570-e747d7d9dd76: 'Schedule Section' # Schedule Section
    a7c7c6e9-f593-4f24-ab19-e958462d56ad: 'Large Textfield Module' # Large Textfield Module
    a9ff56b4-749a-460a-9e89-9fc5230e7e8a: Number # Number
    a11e6e27-7ad7-4273-a667-c62aba611b9c: Groups # Groups
    a82e94c9-64ff-440e-bcac-7b82c8761cd0: 'Footer Image Cards' # Footer Image Cards
    a9805a00-056e-42e5-8555-4b247f60646e: 'Show Image' # Show Image
    accc6cfe-de15-40f6-bed9-40254624cce8: 'Group Class' # Group Class
    b1db83ea-7f9d-448e-aa01-dd1299ba24b1: 'Club Card Module' # Club Card Module
    b3be9a9f-e15c-48f9-8020-ded9bf893725: Extended # Extended
    b4e69c12-ef16-40cd-9c21-2556a3f9a56f: Group # Group
    b38c4205-04c9-4408-ad94-3142832e2787: 'Show List' # Show List
    b40d8450-6dfb-42fd-b59a-8acb9534847b: 'Club Selection' # Club Selection
    ba150bba-13f4-497d-ae2c-5ee54f0f673e: 'Recommendations Module' # Recommendations Module
    bb418bc5-8bcf-4c28-b832-9230996b53ad: 'Hardfacts Matrix' # Hardfacts Matrix
    bb66069f-40f5-4f42-a7fd-21fef987c6b6: Feature # Feature
    bbea2f32-f571-4305-b58b-b3f59e9af047: 'Groups Section' # Groups Section
    bc978765-b473-4a75-b703-5f8ec09931df: Groups # Groups
    be5d824d-92d4-461c-8e59-894657fb6eeb: Contact # Contact
    bebc23d5-2d50-4499-ae0d-6aa66437be5e: Copyright # Copyright
    becfe5ca-3a1d-4962-8fc7-30c4caf3a387: 'Bold Link' # Bold Link
    c3b49286-4ca2-4801-9d33-2a3e31e1807d: Home # Home
    c26a36f0-36c6-42c0-99e0-aa0b4303441c: 'Image 1600x' # Image 1600x
    c47bab61-17f3-469d-9c77-9560c5ae34fb: 'Menu Primary Link' # Menu Primary Link
    c66d9767-f1b8-4fef-82c3-6734d1316a31: 'Two Column Module' # Two Column Module
    c69f0277-c48d-451a-84c1-2b4423aff544: Imprint # Imprint
    c750db9e-77f1-4ee7-9623-ddea660fd8d3: 'FAQ Card' # FAQ Card
    c983ea17-f1cd-41ba-9dc2-55ee24f1fa83: 'Club Card' # Club Card
    c5140b51-0128-49af-9fc0-63fe79c12377: 'Team Member' # Team Member
    c24954e3-8320-487b-87ac-8923abad84c2: Thumbnail # Thumbnail
    c68104aa-08f5-44a5-a8c0-8aca3fba89eb: General # General
    cc7a19fb-9094-46f1-bcff-98d347b3a9cd: Schedule # Schedule
    ccff5e66-8f82-4233-a6da-2adaf6c97ced: Italic # Italic
    cddab166-f11e-4253-9940-1781dd7526c7: Position # Position
    ce490459-dc63-4854-810e-ff2762981c6f: Videos # Videos
    cf6922f9-6cbd-4c4a-b7e7-65bba55e8cfa: Specials # Specials
    cfddac30-3c70-417e-a79d-05e574d4ce9b: 'Header Module' # Header Module
    d3b172bd-4c59-4df0-8f63-761e642c443d: 'List Enabled' # List Enabled
    d9f677d9-2588-446d-abe7-d2721bfa0293: 'Opening Hours' # Opening Hours
    d44e6719-a89d-4efb-933e-94ccf80c8677: 'Image Module' # Image Module
    da24f035-94c4-4102-8f2e-4cfec6616053: Surname # Surname
    da87989f-6fba-4fb3-afae-2501b651f019: 'Alt Text' # Alt Text
    dc2106a7-fc66-4e10-bf53-98bc11ae1f2c: About # About
    ddb7cef7-5099-40d3-a1c7-a70450c6c444: 'Team Member List Module' # Team Member List Module
    de42d2ef-eced-4823-8667-8e4fab66c577: Label # Label
    de666abc-e71d-43e3-b318-cc6d8044b6b9: manhattan # manhattan
    e0d3261a-1f53-4699-8019-52cc167ef7a8: 'Feature Card Matrix' # Feature Card Matrix
    e011b6d5-dcbb-4da3-9dce-001b650b9f46: Club # Club
    e03a4c4e-2c39-4f7b-92ee-2145a16e7b60: 'Group Type' # Group Type
    e065e8b8-5e38-4a95-a799-7ca47d78855b: Name # Name
    e3cac887-0183-47ec-b970-f95ea68a80b4: Description # Description
    e8b0c6b4-54c0-448d-8d0c-6ee41ce9345b: 'Group Class' # Group Class
    e9a7cf94-4d4c-47fb-8eb0-76c7a3edf0de: 'About Section' # About Section
    e9bcbfad-06b8-466d-b605-34bb3a34f00f: 'Metadata List' # Metadata List
    e65df9b6-f654-4750-b847-46e355ec1c39: 'Website Contact' # Website Contact
    e344ac15-6d4b-4dca-a3e3-a23af0036956: 'Metadata Image' # Metadata Image
    e414d637-e54f-4359-9cf8-cd94185009c4: Imprint # Imprint
    e532cedd-0979-454d-a439-abbd2422f2f2: 'Hardfacts Card' # Hardfacts Card
    e2752575-679f-49dc-be7c-983dcee237ba: manhattan-en # manhattan-en
    ead07398-7b50-4558-9d45-db3e07f8c010: Trainer # Trainer
    eb740701-1a67-4df7-9dc9-92f7801b5692: 'Contact Form' # Contact Form
    ebe99fa9-44bc-452d-93db-18269c34470c: 'Footer Row' # Footer Row
    ef976d27-53b3-47a5-8757-ed925f83dd77: 'List Matrix' # List Matrix
    f1f84e81-4f8a-443b-acac-309e7aac4ee4: 'Bold Italic Link Bullets Headline' # Bold Italic Link Bullets Headline
    f8da3357-a4e6-4a71-837b-d7d488bc88b2: 'Link To Page' # Link To Page
    f11fe25c-1cb4-461e-9f1b-e914ccf49ded: 'Club Hardfact' # Club Hardfact
    f23e2f8b-bbda-495c-ac64-8fc0acbaa858: New # New
    f91ce7e1-cbcf-480c-a150-4bef0425b40d: 'Trainers Section' # Trainers Section
    f329a093-89dd-4fd5-92c6-beb411ab6692: 'Is Call To Action' # Is Call To Action
    f7887332-7c4f-4b84-b93e-f0317ef1572a: 'Header Asset' # Header Asset
    f9361309-ad72-4f78-8e94-6d114a57b969: 'Social Link' # Social Link
    fa0e872b-1154-46fa-9d1e-5e067173bdc7: 'Contact Form Module' # Contact Form Module
    fe9059e0-6c6e-477b-b7a6-dbfeff986f2c: 'Showing Both' # Showing Both
plugins:
  calendar:
    edition: pro
    enabled: true
    licenseKey: GP7RR3FTHIGMEA9LOJ1ZC87X
    schemaVersion: 5.0.1
    settings:
      allDay: false
      authoredEventEditOnly: false
      defaultView: week
      demoBannerDisabled: null
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: -1
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: null
      quickCreateEnabled: true
      showDisabledEvents: true
      showMiniCal: true
      timeFormat: auto
      timeInterval: 30
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 3Q1K6A7ZE0F3GJ77JAAVD0O8
    schemaVersion: 3.4.12
system:
  edition: solo
  live: true
  name: $DDEV_PROJECT
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
