fieldLayouts:
  a255a008-c212-4a9b-8b21-695e145156a2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-30T09:13:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 48922ed3-f535-4fed-9f81-9b7c5093f00e # List
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e2f0dfa-c694-46a0-a78c-64d07c83519f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-30T09:13:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 532d7638-9f59-41af-91d2-46ddf87a3911 # Additional Info Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d87399-a637-4272-8b98-b14a8ce20ab3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9951c68b-dd85-44de-9c44-93b50e0fa9d1
        userCondition: null
    thumbFieldKey: null
handle: calendar
name: Calendar
sortOrder: 7
