fieldLayouts:
  aafd35a5-c763-4a8d-a028-6b8b617cae7e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-18T15:48:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a82e94c9-64ff-440e-bcac-7b82c8761cd0 # Footer Image Cards
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5f13fb7-5ecc-41fe-a734-c2de50da31d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-18T15:48:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 85bf4b4f-4f28-4742-9bb7-1497231dc4bb # Footer Rows
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de9ce4f9-fc50-4400-8a55-e314161f9cde
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T12:03:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 89a65ca6-59b1-4161-a8ca-e27dc33a1765 # Social Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 572e0f43-2d02-40e0-861b-76915a262f4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-19T07:59:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bebc23d5-2d50-4499-ae0d-6aa66437be5e # Copyright
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82b6d2c5-bb21-4086-b354-84a44c78c044
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52fd3633-c17f-428b-a3ca-cf9dd86c0933
        userCondition: null
    thumbFieldKey: null
handle: footer
name: Footer
sortOrder: 6
