defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 11dedd21-c9e4-4490-8ed2-ee30e10e3b4d # Accessibility Section
handle: accessibility
maxAuthors: 1
name: Accessibility
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: _layouts/accessibility.twig
    uriFormat: '{slug}'
  e2752575-679f-49dc-be7c-983dcee237ba: # manhattan-en
    enabledByDefault: true
    hasUrls: true
    template: _layouts/accessibility.twig
    uriFormat: '{slug}'
type: single
