defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 310af722-4e91-4858-a3c5-35d1117e8a4e # AGB Section
handle: agb
maxAuthors: 1
name: AGB
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: _layouts/agb.twig
    uriFormat: '{slug}'
  e2752575-679f-49dc-be7c-983dcee237ba: # manhattan-en
    enabledByDefault: true
    hasUrls: true
    template: _layouts/agb.twig
    uriFormat: '{slug}'
type: single
