defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2fbb02d0-7852-4eee-b721-807b931e788f # FAQ Section
handle: faq
maxAuthors: 1
name: FAQ
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: _layouts/faq.twig
    uriFormat: faq
  e2752575-679f-49dc-be7c-983dcee237ba: # manhattan-en
    enabledByDefault: true
    hasUrls: true
    template: _layouts/faq.twig
    uriFormat: faq
type: single
