defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 77a9e634-565d-4610-8aea-d10dd619f000 # Privacy
handle: privacy
maxAuthors: 1
name: Privacy
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: _layouts/privacy.twig
    uriFormat: privacy
type: single
