defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6147a940-8c22-46a2-8719-b8518c60469b # Specials Section
handle: specials
maxAuthors: 1
name: Specials
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: specials/_entry.twig
    uriFormat: 'specials/{slug}'
  e2752575-679f-49dc-be7c-983dcee237ba: # manhattan-en
    enabledByDefault: true
    hasUrls: true
    template: specials/_entry.twig
    uriFormat: 'specials/{slug}'
type: channel
