defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f91ce7e1-cbcf-480c-a150-4bef0425b40d # Trainers Section
handle: trainers
maxAuthors: 1
name: Trainers
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  731c4afc-3bf9-4c58-a826-7db0350cadfd: # manhattan-de
    enabledByDefault: true
    hasUrls: true
    template: _layouts/trainers.twig
    uriFormat: '{slug}'
  e2752575-679f-49dc-be7c-983dcee237ba: # manhattan-en
    enabledByDefault: true
    hasUrls: true
    template: _layouts/trainers.twig
    uriFormat: '{slug}'
type: single
